export const siteConfig = {
  name: 'Darul Qurra',
  locationLabel: 'Peshawar, KP, Pakistan',
  city: 'Peshawar',
  province: 'KP',
  country: 'Pakistan',
  phone: '(091) 2210650',
  phoneHref: 'tel:(091) 2210650',
  whatsapp: '+92 300 123 4567',
  email: 'darulqurra@gmail.com',
  emailHref: 'mailto:darulqurra@gmail.com',
  admissionsEmail: 'darulqurra@gmail.com',
  admissionsEmailHref: 'mailto:darulqurra@gmail.com',
  address: 'Darul Qurra, Madni Masjid Namak Mandi, Peshawar KP, Pakistan',
  officeHours: 'Mon-Sat: 08:00 AM - 05:00 PM',
  establishedYear: 1969,
};
